import { Providers } from "./providers";
import "./globals.css";

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body>
                <div
                    data-tauri-drag-region=""
                    className="w-full h-6 text-center cursor-pointer bg-content1 fixed top-0 z-50"
                >
                    DevUtils
                </div>
                <Providers>{children}</Providers>
            </body>
        </html>
    );
}
